name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        # Skip post-install to avoid malicious scripts stealing PAT
        run: npm install --ignore-script
        env:
          # GITHUB_TOKEN can't access packages hosted in private repos,
          # even within the same organisation
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Post-install
        run: npm rebuild && npm run prepare --if-present
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
