name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          # Use PAT instead of default Github token, because the default
          # token deliberately will not trigger another workflow run
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        # Skip post-install to avoid malicious scripts stealing PAT
        run: npm install --ignore-script
        env:
          # GITHUB_TOKEN can't access packages hosted in private repos,
          # even within the same organisation
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Post-install
        run: npm rebuild && npm run prepare --if-present
      - name: Test
        run: npm test
      - name: Tag
        if: ${{ github.ref == 'refs/heads/master' }}
        run: ./tag.sh
